### ISSUE TITLE
Handling arbitrary object motion 

### ISSUE THREAD

**Issue by xiexh20** [griffbr/ODMD#9]
Hello, 

Thanks for the great work, it is amazing!
While reading the paper, I am wondering if the model can still work under complex object/camera motions? To the best of my reading, currently, the camera motion is limited to translation along x, y, and z-axis. Will it still work if there is some rotation of the camera or the object? For example, a pedestrian squat, or the camera is tilt by some angle?

Best,
Xianghui

**Comment by griffbr** [comment]
Hello Xianghui,

Thank you for your insightful question and kind words.

You are correct that the paper's analytical model is most accurate without rotation (Section 3.1, Motion and Detection Inputs). Nonetheless, the paper reports Driving results (Figure 6, center) that include camera rotation from vehicle turning (for more info on the Driving Set, see Section 5.2 [here](https://arxiv.org/pdf/2007.05676)). Basically, the learned DBox model can handle some rotation and still provide a decent estimate. This is because DBox is trained under purposefully perturbed conditions (Section 3.3, Learning which Observations to Trust) to learn depth estimation even in conditions where the underlying analytical model is inaccurate.

Still, if you want to train a model that is especially accurate in conditions with camera rotation, you can modify our code and include camera rotation as a perturbation or even as an explicit input. I'm not saying this would be easy, but it could produce some very interesting results and be a substantial contribution in terms of opening this work up to applications with substantially more camera rotation than the driving, robotics, and camera phone examples we tested. If you want to take this approach, I would just advise you that you consider 1) there are no monocular depth cues from rotation alone and 2) objects are more likely to enter and leave view with substantial rotation.

Thank you again for your question and interest in this work.

Best,
Brent

**Comment by xiexh20** [comment]
Dear Brent, 

Thank you so much for your elaborated reply. It is really helpful. 
I was mainly concerned with the effect of camera motion as in lots of cases the hand-held camera can undergo some rotation. It is interesting that this network still works quite well. 
Thanks for your great work and good luck with your future research!

Best,
Xianghui
